# Generated by Django 3.2.4 on 2021-06-21 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GitHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=256)),
                ('picture', models.ImageField(upload_to='links/')),
            ],
        ),
        migrations.CreateModel(
            name='HardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_lvl', models.CharField(choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper intermediate'), ('C1', 'Advanced'), ('C2', 'Mastery')], max_length=20)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=6)),
                ('last_name', models.CharField(max_length=10)),
                ('age', models.DateField()),
                ('avatar', models.ImageField(upload_to='users/avatar/')),
                ('description', models.TextField(max_length=5000)),
                ('extra_skills', models.ManyToManyField(to='about.ExtraSkill')),
                ('github', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='about.github')),
                ('hard_skills', models.ManyToManyField(to='about.HardSkill')),
                ('soft_skills', models.ManyToManyField(to='about.SoftSkill')),
            ],
        ),
    ]
