# Generated by Django 3.2.4 on 2021-06-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extraskill',
            options={'verbose_name': 'ExtraSkill', 'verbose_name_plural': 'ExtraSkills'},
        ),
        migrations.AlterModelOptions(
            name='github',
            options={'verbose_name': 'GitHub', 'verbose_name_plural': 'GitHubs'},
        ),
        migrations.AlterModelOptions(
            name='hardskill',
            options={'verbose_name': 'HardSkill', 'verbose_name_plural': 'HardSkills'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Resume', 'verbose_name_plural': 'Resumes'},
        ),
        migrations.AlterModelOptions(
            name='softskill',
            options={'verbose_name': 'SoftSkill', 'verbose_name_plural': 'SoftSkills'},
        ),
    ]
