# Generated by Django 3.2.4 on 2021-06-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20210621_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='english_lvl',
            new_name='english_lvls',
        ),
    ]
