# Generated by Django 3.2.4 on 2021-06-26 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='projects/')),
                ('description', models.TextField(max_length=5000)),
                ('link', models.CharField(max_length=256)),
                ('Technologies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.technology')),
            ],
            options={
                'verbose_name': 'PetProject',
                'verbose_name_plural': 'PetProjects',
            },
        ),
    ]
