# Generated by Django 3.2.4 on 2021-06-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Technologies',
        ),
        migrations.AddField(
            model_name='project',
            name='Technologies',
            field=models.ManyToManyField(to='projects.Technology'),
        ),
    ]
