# Generated by Django 3.2.4 on 2021-06-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ReadMe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
